services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: tusenti
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    build: .
    ports:
      - 5000:5000
      - 9229:9229  # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    depends_on:
      - postgres
    environment:
      # add the following      
      DATABASE_URL: postgres://postgres@postgres/tusenti
      PORT: 5000
      
